id: P000088
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །རྒྱུ་འབྲས་རྐྱེན་གསུམ་གྱི་དཀའ་འགྲེལ་བློ་གསལ་མིག་འབྱེད་ཅེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མང་ཐོས་ཀླུ་སྒྲུབ་རྒྱ་མཚོ།
  layers:
  - book_title
  - author
  - quotation
  id: IBA-LG-02-1
web_metadata:
  title:
    en: Opening the Eye to Clear Understanding:A Clarification on Causes, Results,
      and Factors
    bo: རྒྱུ་འབྲས་རྐྱེན་གསུམ་གྱི་དཀའ་འགྲེལ་བློ་གསལ་མིག་འབྱེད།
  collection:
    en: IBA Ludrup Gyatso Series–  Book 2
    bo: ཀླུ་སྒྲུབ་རྒྱ་མཚོ་རྩོམ་བྲིས།–  དེབ། ༢
  author:
    en: Mangtho Ludrup Gyatso
    bo: མང་ཐོས་ཀླུ་སྒྲུབ་རྒྱ་མཚོ།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-LG-02-1
  category:
    en: Abhidharma
    bo: ཆོས་མངོན་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-LG-02-1.epub
  description:
    en: The new light on the chapter offacultiesfrom Abhidharma deals with the aspects
      of causes, conditions and results.
    bo: ཆོས་མངོན་པའི་གཞུང་གི་དབང་པོ་བསྟན་པའི་ལེའུ་ལས་འཕྲོ་པའི་རྒྱུ་འབྲས་དང་དེའི་རྐྱེན་སོགས་སྐོར་རྒྱས་པར་བཞུགས་ཡོད།
